import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { customers } from './demo-data';

@Component({
  selector: 'app-customer-page', imports: [RouterLink], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <a routerLink="/clientes" class="link link-hover text-sm">← Voltar aos clientes</a>
    @if (isNew()) {
      <div class="mt-5 max-w-3xl"><h1 class="text-3xl font-bold">Inscrever sócio</h1><p class="mt-2 text-base-content/65">O número de inscrição será gerado ao salvar no servidor.</p>
        <form class="mt-6 rounded-box border border-base-300 bg-base-100 p-6" (submit)="$event.preventDefault()">
          <div class="grid gap-4 sm:grid-cols-2"><label class="block sm:col-span-2"><span class="mb-1 block text-sm font-medium">Nome completo *</span><input class="input w-full" required /></label><label class="block"><span class="mb-1 block text-sm font-medium">CPF *</span><input class="input w-full" inputmode="numeric" required /></label><label class="block"><span class="mb-1 block text-sm font-medium">Telefone *</span><input class="input w-full" type="tel" required /></label><label class="block"><span class="mb-1 block text-sm font-medium">Data de nascimento *</span><input class="input w-full" type="date" required /></label><label class="block"><span class="mb-1 block text-sm font-medium">Sexo *</span><select class="select w-full" required><option value="">Selecione</option><option>Feminino</option><option>Masculino</option><option>Outro</option><option>Prefiro não informar</option></select></label><label class="block sm:col-span-2"><span class="mb-1 block text-sm font-medium">Endereço *</span><input class="input w-full" required /></label></div>
          <div class="alert alert-info mt-6 text-sm">Cadastro de demonstração. A inscrição será disponibilizada após integração com a API.</div><button class="btn btn-primary mt-5" type="button" disabled>Salvar inscrição</button>
        </form></div>
    } @else if (customer()) {
      <div class="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm text-base-content/60">Inscrição {{ customer()?.registration }} · {{ customer()?.type }}</p><h1 class="mt-1 text-3xl font-bold">{{ customer()?.name }}</h1><span class="badge mt-3" [class.badge-success]="customer()?.status === 'Ativo'" [class.badge-ghost]="customer()?.status !== 'Ativo'">{{ customer()?.status }}</span></div><a class="btn btn-outline" [routerLink]="['/clientes', customer()?.id]" [queryParams]="{ editar: 1 }">Editar cliente</a></div>
      <div class="mt-7 grid gap-6 lg:grid-cols-[1fr_320px]"><section class="rounded-box border border-base-300 bg-base-100 p-6"><h2 class="text-xl font-bold">Dados do cliente</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-sm text-base-content/60">Tipo</dt><dd class="font-medium">{{ customer()?.type }}</dd></div><div><dt class="text-sm text-base-content/60">Situação</dt><dd class="font-medium">{{ customer()?.status }}</dd></div><div><dt class="text-sm text-base-content/60">Número de inscrição</dt><dd class="font-medium">{{ customer()?.registration }}</dd></div>@if (customer()?.holder) { <div><dt class="text-sm text-base-content/60">Sócio responsável</dt><dd class="font-medium">{{ customer()?.holder }}</dd></div> }</dl><p class="mt-6 text-sm text-base-content/60">Dados pessoais adicionais serão exibidos após integração com a API.</p></section>
      <aside class="space-y-5"><section class="rounded-box border border-base-300 bg-base-100 p-6"><h2 class="text-lg font-bold">Dependentes</h2>@if (customer()?.type === 'Sócia' || customer()?.type === 'Sócio') { <p class="mt-2 text-sm text-base-content/65">{{ customer()?.dependents }} de 3 dependentes ativos no exemplo.</p><a class="btn btn-sm mt-4" [class.btn-disabled]="(customer()?.dependents || 0) >= 3" [attr.aria-disabled]="(customer()?.dependents || 0) >= 3" [routerLink]="(customer()?.dependents || 0) >= 3 ? null : ['/clientes', customer()?.id]" [queryParams]="{ dependente: 1 }">Adicionar dependente</a> } @else { <p class="mt-2 text-sm text-base-content/65">Vinculado a um sócio.</p> }</section><section class="rounded-box border border-base-300 bg-base-100 p-6"><h2 class="text-lg font-bold">Situação do cadastro</h2><p class="mt-2 text-sm text-base-content/65">Ao desativar um sócio, seus dependentes também são desativados.</p><div class="mt-4 flex flex-wrap gap-2"><button class="btn btn-sm" (click)="statusDialog.showModal()">{{ customer()?.status === 'Ativo' ? 'Desativar' : 'Reativar' }}</button><button class="btn btn-error btn-outline btn-sm" (click)="deleteDialog.showModal()">Excluir</button></div></section></aside></div>
      <dialog #statusDialog class="modal"><div class="modal-box"><h2 class="text-lg font-bold">Alterar situação do cliente?</h2><p class="mt-3 text-sm">Ao desativar um sócio, seus dependentes também serão desativados. A API confirmará quais dependentes podem ser reativados.</p><div class="modal-action"><form method="dialog"><button class="btn">Voltar</button></form><button class="btn btn-primary" disabled>Confirmar alteração</button></div></div><form method="dialog" class="modal-backdrop"><button>Fechar</button></form></dialog>
      <dialog #deleteDialog class="modal"><div class="modal-box"><h2 class="text-lg font-bold">Excluir cliente?</h2><p class="mt-3 text-sm">A exclusão será bloqueada se o cliente ou seus dependentes tiverem histórico de locações.</p><div class="modal-action"><form method="dialog"><button class="btn">Voltar</button></form><button class="btn btn-error" disabled>Confirmar exclusão</button></div></div><form method="dialog" class="modal-backdrop"><button>Fechar</button></form></dialog>
      @if (editing()) { <section class="mt-6 max-w-3xl rounded-box border border-base-300 bg-base-100 p-6"><h2 class="text-xl font-bold">Editar cliente</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="block sm:col-span-2"><span class="mb-1 block text-sm font-medium">Nome completo *</span><input class="input w-full" [value]="customer()?.name" /></label><label class="block"><span class="mb-1 block text-sm font-medium">Data de nascimento *</span><input class="input w-full" type="date" /></label><label class="block"><span class="mb-1 block text-sm font-medium">Sexo *</span><select class="select w-full"><option value="">Selecione</option><option>Feminino</option><option>Masculino</option><option>Outro</option></select></label>@if (customer()?.type === 'Sócia' || customer()?.type === 'Sócio') { <label class="block"><span class="mb-1 block text-sm font-medium">Telefone *</span><input class="input w-full" type="tel" /></label><label class="block"><span class="mb-1 block text-sm font-medium">CPF *</span><input class="input w-full" inputmode="numeric" /></label><label class="block sm:col-span-2"><span class="mb-1 block text-sm font-medium">Endereço *</span><input class="input w-full" /></label> }</div><p class="mt-4 text-sm text-base-content/60">O número de inscrição é permanente e não pode ser alterado.</p><button class="btn btn-primary mt-5" disabled>Salvar alterações</button></section> }
      @if (showDependent()) { <section class="mt-6 max-w-3xl rounded-box border border-base-300 bg-base-100 p-6"><h2 class="text-xl font-bold">Adicionar dependente</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="block sm:col-span-2"><span class="mb-1 block text-sm font-medium">Nome completo *</span><input class="input w-full" /></label><label class="block"><span class="mb-1 block text-sm font-medium">Data de nascimento *</span><input class="input w-full" type="date" /></label><label class="block"><span class="mb-1 block text-sm font-medium">Sexo *</span><select class="select w-full"><option value="">Selecione</option><option>Feminino</option><option>Masculino</option><option>Outro</option></select></label></div><button class="btn btn-primary mt-5" disabled>Salvar dependente</button></section> }
    } @else { <div role="status" class="alert alert-warning mt-6">Cliente de demonstração não encontrado.</div> }`,
})
export class CustomerPage {
  private readonly route = inject(ActivatedRoute);
  private readonly params = toSignal(this.route.paramMap, { initialValue: this.route.snapshot.paramMap });
  private readonly query = toSignal(this.route.queryParamMap, { initialValue: this.route.snapshot.queryParamMap });
  readonly isNew = computed(() => this.route.snapshot.routeConfig?.path === 'clientes/novo');
  readonly customer = computed(() => customers.find((item) => item.id === Number(this.params().get('id'))));
  readonly showDependent = computed(() => this.query().has('dependente'));
  readonly editing = computed(() => this.query().has('editar'));
}
