import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { toSignal } from '@angular/core/rxjs-interop';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { customers, items, rentals } from './demo-data';

@Component({
  selector: 'app-rental-page', imports: [DatePipe, RouterLink], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <a routerLink="/locacoes" class="link link-hover text-sm">← Voltar às locações</a>
    @if (mode() === 'new') {
      <section class="mt-5 max-w-3xl"><h1 class="text-3xl font-bold">Nova locação</h1><p class="mt-2 text-base-content/65">Selecione um cliente e um exemplar físico disponível.</p>
        <div class="mt-6 rounded-box border border-base-300 bg-base-100 p-6"><div class="grid gap-4 sm:grid-cols-2"><label class="block"><span class="mb-1 block text-sm font-medium">Cliente *</span><select class="select w-full"><option value="">Selecione um cliente</option>@for (customer of customers; track customer.id) { <option [value]="customer.id" [disabled]="customer.status !== 'Ativo'">{{ customer.name }} · {{ customer.registration }}</option> }</select></label><label class="block"><span class="mb-1 block text-sm font-medium">Exemplar disponível *</span><select class="select w-full"><option value="">Selecione um item</option>@for (item of items; track item.id) { <option [value]="item.id" [disabled]="item.status !== 'Disponível'">{{ item.name }} · {{ item.extra }}</option> }</select></label><label class="block"><span class="mb-1 block text-sm font-medium">Valor da locação (R$)</span><input class="input w-full" type="number" min="0" step="0.01" placeholder="Sugerido pela API" /></label><label class="block"><span class="mb-1 block text-sm font-medium">Devolução prevista</span><input class="input w-full" type="date" /></label></div><div class="alert alert-info mt-6 text-sm">Disponibilidade, elegibilidade, valor e prazo serão confirmados pela API antes de salvar.</div><button class="btn btn-primary mt-5" disabled>Registrar locação</button></div>
      </section>
    } @else if (mode() === 'return') {
      <section class="mt-5 max-w-3xl"><h1 class="text-3xl font-bold">Registrar devolução</h1><p class="mt-2 text-base-content/65">Localize a locação vigente pelo número de série do exemplar.</p><div class="mt-6 rounded-box border border-base-300 bg-base-100 p-6"><label class="block"><span class="mb-1 block text-sm font-medium">Número de série *</span><input class="input w-full" type="search" placeholder="Ex.: DVD-00129" /></label><div class="mt-6 border-t border-base-300 pt-5"><h2 class="text-lg font-bold">Resumo da devolução</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-base-content/60">Locação vigente</dt><dd>Aguardando consulta</dd></div><div><dt class="text-sm text-base-content/60">Atraso</dt><dd>Aguardando consulta</dd></div><div><dt class="text-sm text-base-content/60">Multa aplicada</dt><dd>Informada pela API</dd></div><div><dt class="text-sm text-base-content/60">Total devido</dt><dd>Informado pela API</dd></div></dl></div><div class="alert alert-info mt-6 text-sm">A consulta por série e o cálculo do valor devido estarão disponíveis após a integração.</div><button class="btn btn-primary mt-5" disabled>Confirmar devolução</button></div></section>
    } @else if (rental()) {
      <div class="mt-5 flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm text-base-content/60">Locação de demonstração #{{ rental()?.id }}</p><h1 class="mt-1 text-3xl font-bold">{{ rental()?.title }}</h1><span class="badge mt-3" [class.badge-warning]="rental()?.status === 'Em atraso'" [class.badge-success]="rental()?.status === 'Devolvida'">{{ rental()?.status }}</span></div><div class="flex flex-wrap gap-2"><a class="btn" [routerLink]="['/locacoes', rental()?.id]" [queryParams]="{ editar: 1 }">Alterar</a><button class="btn btn-error btn-outline" (click)="cancelDialog.showModal()">Cancelar locação</button></div></div>
      <div class="mt-7 grid gap-6 lg:grid-cols-[1fr_320px]"><section class="rounded-box border border-base-300 bg-base-100 p-6"><h2 class="text-xl font-bold">Dados da locação</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2"><div><dt class="text-sm text-base-content/60">Cliente</dt><dd class="font-medium">{{ rental()?.customer }}</dd></div><div><dt class="text-sm text-base-content/60">Exemplar</dt><dd class="font-medium">{{ rental()?.serial }}</dd></div><div><dt class="text-sm text-base-content/60">Data da locação</dt><dd class="font-medium">{{ rental()?.date | date:'dd/MM/yyyy':'':'pt-BR' }}</dd></div><div><dt class="text-sm text-base-content/60">Devolução prevista</dt><dd class="font-medium">{{ rental()?.due | date:'dd/MM/yyyy':'':'pt-BR' }}</dd></div><div><dt class="text-sm text-base-content/60">Valor</dt><dd class="font-medium">{{ rental()?.price }}</dd></div><div><dt class="text-sm text-base-content/60">Pagamento</dt><dd class="font-medium">A confirmar pela API</dd></div><div><dt class="text-sm text-base-content/60">Devolução efetiva</dt><dd class="font-medium">A confirmar pela API</dd></div><div><dt class="text-sm text-base-content/60">Multa aplicada</dt><dd class="font-medium">A confirmar pela API</dd></div></dl></section><aside class="rounded-box border border-base-300 bg-base-100 p-6"><h2 class="text-lg font-bold">Atendimento</h2><p class="mt-2 text-sm text-base-content/65">Locações pagas não podem ser canceladas. O servidor informará o motivo de qualquer bloqueio.</p><a routerLink="/locacoes/devolucao" class="btn btn-sm mt-5">Ir para devolução</a></aside></div>
      <dialog #cancelDialog class="modal"><div class="modal-box"><h2 class="text-lg font-bold">Cancelar locação?</h2><p class="mt-3 text-sm">Locações pagas não podem ser canceladas. A situação do pagamento será confirmada pela API.</p><div class="modal-action"><form method="dialog"><button class="btn">Voltar</button></form><button class="btn btn-error" disabled>Confirmar cancelamento</button></div></div><form method="dialog" class="modal-backdrop"><button>Fechar</button></form></dialog>
      @if (editing()) { <section class="mt-6 max-w-3xl rounded-box border border-base-300 bg-base-100 p-6"><h2 class="text-xl font-bold">Alterar locação</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="block"><span class="mb-1 block text-sm font-medium">Valor (R$)</span><input class="input w-full" type="number" min="0" step="0.01" /></label><label class="block"><span class="mb-1 block text-sm font-medium">Devolução prevista</span><input class="input w-full" type="date" [value]="rental()?.due" /></label></div><button class="btn btn-primary mt-5" disabled>Salvar alterações</button></section> }
    } @else { <div role="status" class="alert alert-warning mt-6">Locação de demonstração não encontrada.</div> }`,
})
export class RentalPage {
  private readonly route = inject(ActivatedRoute);
  private readonly params = toSignal(this.route.paramMap, { initialValue: this.route.snapshot.paramMap });
  private readonly query = toSignal(this.route.queryParamMap, { initialValue: this.route.snapshot.queryParamMap });
  readonly customers = customers; readonly items = items;
  readonly mode = computed(() => this.route.snapshot.routeConfig?.path === 'locacoes/nova' ? 'new' : this.route.snapshot.routeConfig?.path === 'locacoes/devolucao' ? 'return' : 'detail');
  readonly rental = computed(() => rentals.find((item) => item.id === Number(this.params().get('id'))));
  readonly editing = computed(() => this.query().has('editar'));
}
